### ISSUE TITLE
Try to build the project

### ISSUE THREAD

**Issue by mmoya** [merchise/fortaleza#2]
Research how to build the game (turbopascal on a DOS emulator, freepascal?) and document the process.

**Comment by mmoya** [comment]
Start by installing FreePascal Compiler (FPC) and running it as `fpc -Mtp -O- -Rintel FORT1.PAS`. I'm testing with FPC 3.0.4 on a modern x86_64 system.

`TELETYPE.PAS` is the one failing because of all of the assembler involved.

**Comment by greenled** [comment]
Any word from the original developers?

**Comment by mmoya** [comment]
Regarding this issue, the original developer is not involved in any way. This is a community effort.

Take in account this is code from almost 3 decades ago and people usually move on to other projects. The original developer provided a link to the builds in case you want to play the game. They are in the README.

**Comment by med-merchise** [comment]
@jromero2k is considered a original developer, not the author, but he had a crucial role in the second version. He is starting to participate here.

**Comment by jorgeamadosoria** [comment]
Any thoughts on porting the code to a more modern language? Java, for example?

**Comment by mmoya** [comment]
Read [here][1] starting from _I haven’t written Turbo Pascal in about 25 years, but do you ever really forget?_ There is a thing called DOSBox-X and a copy of Turbo Pascal 7.0.

It might be a more practical approach than building with FPC.  

[1]: https://bert.org/2021/01/04/t2-pin-cracking/

**Comment by davidmpaz** [comment]
Hi,

i did came late to the party. But since i am another nostalgic who did enjoy this game, here’s my 5 cents.

First step was to explore the Free Pascal solution. It was a dead end to me as it is documented in [this issue](https://gitlab.com/freepascal.org/fpc/source/-/issues/39489).

Second step was to achieve some setup with DOSBox and Turbo Pascal. Results are in this repository: https://github.com/davidmpaz/docker-dosbox.

Since i did not found any way to automate the Turbo Pascal installation ;-) next step was just to create the container, install the TP manually and push the image to docker hub so other can just use it as is, it is under: https://hub.docker.com/repository/docker/davidmpaz/dosbox-tp7

Since the base image used installs a vnc server, if you just want to play, this is enough. You only have to mount a volume to access the [executable](https://ia800901.us.archive.org/11/items/FORT1/FORT1.EXE) from inside dosbox and that's it.

After installing TPC, i got this error when building FORT1.PAS file:

<img width="709" alt="Bildschirmfoto 2022-01-01 um 13 25 31" src="https://user-images.githubusercontent.com/210742/147882333-045f0d83-1643-435f-ae12-c83f66700e7a.png">

This error posed another goal, to obtain the object file from the assembler code. It can be checked the branches in the repository, `masm-6-15` and `ta-2.0`. MAS32 did not worked under MS-DOS, as well as MASM v6.15, the error was **This Program Cannot Be Run in DOS Mode**. Then i tried to use Turbo Assembler, the error was then:

<img width="702" alt="Bildschirmfoto 2022-01-02 um 16 49 39" src="https://user-images.githubusercontent.com/210742/147882459-9423f700-7f4c-4d81-bf4a-247c98189155.png">

which makes me think that, either the file got mangled with the encoding or the Assembler is not understood by TA-2.0. Could we confirm that the encoding of the .ASM file is correct as well as the code the file contains?

Currently, i just ran out of ideas, so a pause will be made :) ... next steps would be to manage to compile the project fully, and then, configure dosbox auto-exec to run the compilation process as a batch when dosbox start. That would allow to use the build setup in a pipeline if needed.

Another repository that worth mentioning is: https://github.com/johangardhage/dos-tpdemos

Hope this helps,
Chers,
David

**Comment by mmoya** [comment]
Hi, David

I've take a look and the file is [obviously mangled](https://github.com/merchise/fortaleza/blob/master/WIN.ASM#L127-L166), the same it was with `CASTLES.PAS`. @rsotolongo can you check if you have a correct `WIN.ASM` in your local copy? Thanks.

**Comment by mmoya** [comment]
> which makes me think that, either the file got mangled with the encoding or the Assembler is not understood by TA-2.0. Could we confirm that the encoding of the .ASM file is correct as well as the code the file contains?

@davidmpaz `WIN.ASM` is fixed now by #6. Can you try again to build the project?

**Comment by davidmpaz** [comment]
Hi, 

take a look to the pull request please. I can provide more documentation if required. Now it is possible to fully build the project!

One thing to note, there are still files uncompleted or mangled. Once all these issues are resolved, anyone can build this project using the provided tools.

Cheers,
David
